create table
  public.bookings (
    id integer generated by default as identity,
    start_date timestamp with time zone not null,
    end_date timestamp with time zone not null,
    income numeric(10, 2) not null,
    house_id integer not null,
    guests smallint not null default '1'::smallint,
    constraint bookings_pkey primary key (id),
    constraint bookings_id_key unique (id),
    constraint bookings_house_id_fkey foreign key (house_id) references houses (id)
  ) tablespace pg_default;

create trigger send_booking_notification
after insert on bookings for each row
execute function send_booking_notification ();

create trigger distribute_income_to_investors
after insert on bookings for each row
execute function distribute_income_to_investors_func ();