create table
  public.houses (
    name text not null,
    description text null,
    images text[] null,
    price numeric not null,
    amount_reached integer not null default 0,
    investment_details json not null,
    publishing_date timestamp with time zone not null default now(),
    start_date timestamp with time zone null,
    duration integer not null,
    coords json not null,
    address text not null,
    is_paid boolean not null default false,
    is_ready boolean not null default false,
    id integer generated by default as identity,
    investors text[] null,
    total_required numeric not null,
    airbnb_link text null,
    constraint houses_pkey primary key (id, name),
    constraint houses_id_key unique (id),
    constraint houses_name_key unique (name),
    constraint amount_check check (((amount_reached)::numeric <= total_required))
  ) tablespace pg_default;
